import { IDocumentMock } from "entities/folder";

export const MOCK_DOCUMENT: IDocumentMock[] = [
  {
    id: "1",
    title: "Understanding menopause symptoms",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    readyForReview: true,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "2",
    title: "Weight Gain",
    folder: "Perimenopause",
    attachedFiles: ["file3.txt"],
    instructions: ["Instruction 3"],
    client: ["Client C"],
    status: "ai-generated",
    documentText:
      "This is another sample AI generated document text. It contains information about the document.",
    readyForReview: false,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "3",
    title: "Weight Gain",
    folder: "Perimenopause",
    attachedFiles: ["file4.txt"],
    instructions: ["Instruction 4"],
    client: ["Client D"],
    status: "ai-generated",
    documentText: "Additional AI content about weight gain.",
    readyForReview: true,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "4",
    title: "Weight Gain",
    folder: "Perimenopause",
    attachedFiles: ["file5.txt"],
    instructions: ["Instruction 5"],
    client: ["Client E"],
    status: "ai-generated",
    documentText: "More insights on perimenopausal weight changes.",
    readyForReview: true,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "5",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: false,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "6",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: false,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "7",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: true,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "8",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: true,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "9",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: false,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "10",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: true,
    folderId: "2",
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "11",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewStatus: "waiting",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "12",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewStatus: "second-review",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "13",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewStatus: "under-review",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "14",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewStatus: "waiting",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "15",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewStatus: "waiting",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "16",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewStatus: "waiting",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "17",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewStatus: "second-review",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "18",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewStatus: "under-review",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "19",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewStatus: "waiting",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "20",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    // status: "in-review",
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "2",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "21",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "22",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "23",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "24",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "25",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "26",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "27",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "28",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "29",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "30",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "31",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "32",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "33",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "34",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "35",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "36",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "37",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "38",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "39",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "ready-to-publish",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "3",
    reviewers: ["Jessica Gale MD FDN"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "41",
    title: "Understanding ...",
    folder: "Mood Swings",
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Understanding ...",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Understanding ...",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Understanding ...",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Understanding ...",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Understanding ...",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Understanding ...",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Understanding ...",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Understanding ...",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
  {
    id: "40",
    title: "Understanding ...",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "approved",
    reviewStatus: "published",
    folderId: "4",
    author: "Alice Johnson",
    reviewers: ["Jessica Gale MD CFNP"],
    createdAt: new Date().toISOString(),
    aiTitle: "",
  },
];
