import { IDocument } from "entities/document";

export const MOCK_DOCUMENT: IDocument[] = [
  {
    id: "1",
    title: "Understanding menopause symptoms",
    folder: "Mood Swings",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "ai-generated",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    readyForReview: true,
    folderId: "1",
  },
  {
    id: "2",
    title: "Weight Gain",
    folder: "Perimenopause",
    attachedFiles: ["file3.txt"],
    instructions: ["Instruction 3"],
    client: ["Client C"],
    status: "ai-generated",
    documentText:
      "This is another sample AI generated document text. It contains information about the document.",
    readyForReview: false,
    folderId: "2",
  },
  {
    id: "3",
    title: "Weight Gain",
    folder: "Perimenopause",
    attachedFiles: ["file4.txt"],
    instructions: ["Instruction 4"],
    client: ["Client D"],
    status: "ai-generated",
    documentText: "Additional AI content about weight gain.",
    readyForReview: true,
    folderId: "2",
  },
  {
    id: "4",
    title: "Weight Gain",
    folder: "Perimenopause",
    attachedFiles: ["file5.txt"],
    instructions: ["Instruction 5"],
    client: ["Client E"],
    status: "ai-generated",
    documentText: "More insights on perimenopausal weight changes.",
    readyForReview: true,
    folderId: "2",
  },
  {
    id: "5",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: false,
    folderId: "2",
  },
  {
    id: "6",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: false,
    folderId: "2",
  },
  {
    id: "7",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: true,
    folderId: "2",
  },
  {
    id: "8",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: true,
    folderId: "2",
  },
  {
    id: "9",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: false,
    folderId: "2",
  },
  {
    id: "10",
    title: "Weight Gain",
    folder: "Perimenopause",
    status: "ai-generated",
    readyForReview: true,
    folderId: "2",
  },
  {
    id: "11",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "waiting",
    reviewer: "Jessica Gale MD FDN",
  },
  {
    id: "12",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "second-review",
    reviewer: "Jessica Gale MD FDN",
  },
  {
    id: "13",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "under-review",
    reviewer: "Jessica Gale MD FDN",
  },
  {
    id: "14",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "waiting",
    reviewer: "Jessica Gale MD FDN",
  },
  {
    id: "15",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "waiting",
    reviewer: "Jessica Gale MD FDN",
  },
  {
    id: "16",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "waiting",
    reviewer: "Jessica Gale MD FDN",
  },
  {
    id: "17",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "second-review",
    reviewer: "Jessica Gale MD FDN",
  },
  {
    id: "18",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "under-review",
    reviewer: "Jessica Gale MD FDN",
  },
  {
    id: "19",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "waiting",
    reviewer: "Jessica Gale MD FDN",
  },
  {
    id: "20",
    title: "Hormones 101",
    folder: "Perimenopause",
    attachedFiles: [
      "file1.txt",
      "file2.txt",
      "file3.txt",
      "file4.txt",
      "file5.txt",
    ],
    instructions: ["Instruction 1"],
    client: ["Client A", "Client B", "Client C", "Client D", "Client E"],
    status: "in-review",
    documentText:
      "This is a sample AI generated document text. It contains information about the document.",
    folderId: "1",
    reviewStatus: "waiting",
    reviewer: "Jessica Gale MD FDN",
  },
];
