export const countries = [
  "United States",
  "Canada",
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia, Plurinational State of Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic of the Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of Korea",
  "Korea, Republic of Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of Micronesia",
  "Moldova, Republic of Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela, Bolivarian Republic of Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

export const languages = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Armenian (Eastern)",
  "Armenian (Western)",
  "Azerbaijani (Azeri)",
  "Bassa",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Braille",
  "Bulgarian",
  "Burmese",
  "Cambodian (Khmer)",
  "Cape Verde Creole",
  "Cebuano",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Chuukese",
  "Croatian",
  "Czech",
  "Danish",
  "Dari",
  "Dutch",
  "English",
  "Estonian",
  "Farsi (Persian)",
  "Finnish",
  "Flemmish",
  "French (Canada)",
  "French (France)",
  "Fulani",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hakha Chin",
  "Hakka (Chinese)",
  "Hebrew",
  "Hindi",
  "Hmong",
  "Hungarian",
  "Icelandic",
  "Igbo/Ibo",
  "Ilocano",
  "Ilonggo (Hiligaynon)",
  "Indonesian",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Karen",
  "Kazakh",
  "Kinyarwanda",
  "Kirundi",
  "Korean",
  "Kurdish (Kurmanji dialect)",
  "Kurdish (Sorani dialect)",
  "Kyrgyz/Kirgiz",
  "Lao (Laotian)",
  "Latvian",
  "Lithuanian",
  "Macedonian",
  "Malay (Malaysian)",
  "Mandinka",
  "Marathi",
  "Marshallese",
  "Mien",
  "Mongolian",
  "Montenegrin",
  "Navajo",
  "Nepali",
  "Norwegian",
  "Oromo",
  "Pashto",
  "Polish",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Punjabi",
  "Rohingya",
  "Romanian (Moldavan)",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Somali",
  "Spanish (Castilian)",
  "Spanish (Latin American)",
  "Spanish (other varieties)",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Vietnamese",
  "Wolof",
  "Yoruba",
];

export const raceEthnicity = [
  "Indigenous or Native American",
  "Asian or Asian American",
  "Black or African American",
  "Latino/a/e or Hispanic",
  "Middle Eastern or North African (MENA)",
  "Native Hawaiian or Pacific Islander",
  "European descent",
  "Multiracial (Two or more races)",
  "South Asian",
  "East, Southeast, Central Asian",
  "Ashkenazi or Sephardic Jewish",
  "Romani",
  "Prefer not to say",
  "Other (please specify)",
];

export const householdType = [
  "Single",
  "Living with partner",
  "Living with spouse",
  "Living with parents",
  "With children",
  "Caregiver",
  "Other (please specify)",
];

export const education = [
  "High school or less",
  "Some college",
  "Bachelor's",
  "Master's",
  "Doctorate / Professional",
  "Prefer not to say",
];

export const occupation = [
  "Healthcare Professional",
  "Educator / Academic",
  "Office / Administrative",
  "Skilled trade / Labor",
  "Technology / Engineering",
  "Service industry (e.g. retail, hospitality)",
  "Student / In training",
  "Unemployed / Retired / Other",
  "Other (please specify)",
];

export const CYCLE_HELTH = [
  "Still menstruating",
  "Irregular cycles",
  "No periods for 12+ months",
  "Postmenopausal",
  "Not sure",
  "Not Applicable",
];

export const MAP_CYCLE_HEALTH_TO_TOOLTIP: Record<string, string> = {
  "Still menstruating":
    "You’re having regular monthly periods without major changes in timing or flow.",
  "Irregular cycles":
    "Your periods are becoming unpredictable — shorter, longer, lighter, or heavier than before. This often signals the transition toward menopause (perimenopause).",
  "No periods for 12+ months":
    "You haven’t had a menstrual period for at least a year. This usually marks the natural start of menopause.",
  Postmenopausal:
    "You reached menopause more than a year ago. Your cycle has stopped, and this is the stage after menopause.",
  "Not sure":
    "You’re uncertain where you are in the transition — and that’s completely normal. Tolu will help you track and understand your stage.",
};

export const MAP_MENOPAUSE_STAGE_TO_TOOLTIP: Record<string, string> = {
  Premenopause:
    "You’re having regular monthly periods without major changes in timing or flow.",
  Perimenopause:
    "Your periods are becoming unpredictable — shorter, longer, lighter, or heavier than before. This often signals the transition toward menopause (perimenopause).",
  Menopause:
    "You haven’t had a menstrual period for at least a year. This usually marks the natural start of menopause.",
  Postmenopause:
    "You reached menopause more than a year ago. Your cycle has stopped, and this is the stage after menopause.",
  "Not sure":
    "You’re uncertain where you are in the transition — and that’s completely normal. Tolu will help you track and understand your stage.",
};

export const states = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
