export const countries = [
  "United States",
  "Canada",
  "Germany",
  "Japan",
  "Brazil",
  "Australia",
  "South Africa",
  "India",
];

export const languages = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Armenian (Eastern)",
  "Armenian (Western)",
  "Azerbaijani (Azeri)",
  "Bassa",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Braille",
  "Bulgarian",
  "Burmese",
  "Cambodian (Khmer)",
  "Cape Verde Creole",
  "Cebuano",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Chuukese",
  "Croatian",
  "Czech",
  "Danish",
  "Dari",
  "Dutch",
  "English",
  "Estonian",
  "Farsi (Persian)",
  "Finnish",
  "Flemmish",
  "French (Canada)",
  "French (France)",
  "Fulani",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hakha Chin",
  "Hakka (Chinese)",
  "Hebrew",
  "Hindi",
  "Hmong",
  "Hungarian",
  "Icelandic",
  "Igbo/Ibo",
  "Ilocano",
  "Ilonggo (Hiligaynon)",
  "Indonesian",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Karen",
  "Kazakh",
  "Kinyarwanda",
  "Kirundi",
  "Korean",
  "Kurdish (Kurmanji dialect)",
  "Kurdish (Sorani dialect)",
  "Kyrgyz/Kirgiz",
  "Lao (Laotian)",
  "Latvian",
  "Lithuanian",
  "Macedonian",
  "Malay (Malaysian)",
  "Mandinka",
  "Marathi",
  "Marshallese",
  "Mien",
  "Mongolian",
  "Montenegrin",
  "Navajo",
  "Nepali",
  "Norwegian",
  "Oromo",
  "Pashto",
  "Polish",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Punjabi",
  "Rohingya",
  "Romanian (Moldavan)",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Somali",
  "Spanish (Castilian)",
  "Spanish (Latin American)",
  "Spanish (other varieties)",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Vietnamese",
  "Wolof",
  "Yoruba",
];

export const raceEthnicity = [
  "Indigenous or Native American",
  "Asian or Asian American",
  "Black or African American",
  "Latino/a/e or Hispanic",
  "Middle Eastern or North African (MENA)",
  "Native Hawaiian or Pacific Islander",
  "European descent",
  "Multiracial (Two or more races)",
  "South Asian",
  "East, Southeast, Central Asian",
  "Ashkenazi or Sephardic Jewish",
  "Romani",
  "Prefer not to say",
  "Other (please specify)",
];

export const householdType = [
  "Single",
  "Living with partner",
  "Living with spouse",
  "Living with parents",
  "With children",
  "Caregiver",
  "Other (please specify)",
];

export const education = [
  "High school or less",
  "Some college",
  "Bachelor's",
  "Master's",
  "Doctorate / Professional",
  "Prefer not to say",
];

export const occupation = [
  "Healthcare Professional",
  "Educator / Academic",
  "Office / Administrative",
  "Skilled trade / Labor",
  "Technology / Engineering",
  "Service industry (e.g. retail, hospitality)",
  "Student / In training",
  "Unemployed / Retired / Other",
  "Other (please specify)",
];
