export const API_ROUTES = {
  USER: {
    SET_NEW_PASSWORD: "/user/reset-password",
    EXIST: "/user-exist/{email}",
    SIGNUP: "/user/signup",
    COMPLETE_SIGNUP: "/user/complete-signup",
    LOGIN: "/user/login",
    FORGOT_PASSWORD: "/user/forgot-password",
    PROFILE: "/user/profile",
    DELETE_ACCOUNT: "/user/delete-account",
    VERIFY_RESET_TOKEN: "/user/verify-reset-token",
    ONBOARD_USER: "/coach/onboarding",
    ONBOARD_CLIENT: "/client/onboarding",
    GET_ONBOARDING_USER: "/client/onboarding",
    SIGNOUT: "/user/signout",
  },
  CLIENT: {
    GET_INVITATION_DETAILS: "/client/invitation-details/{token}",
    ACCEPT_COACH_INVITE: "/client/accept-coach-invite",
  },
  AI: {
    SEARCH: "/ai-search/",
    LEARNING_SEARCH: "/ai-learning-search/",
    PERSONALIZED_SEARCH: "/ai-personalized-search/",
    UPDATE_CHAT_TITLE: "/update-chat-title",
    UPDATE_FOLDER_CONTENT: "/update-folder-content",
    DELETE_CHAT: "/chat/{chat_id}",
  },
  SEARCH: {
    HISTORY: "/searched-result/history",
    SESSION: "/session/{chat_id}",
    ADMIN_SESSION: "/admin-session/{chat_id}",
    PERSONALIZED_SESSION: "/personalized-session/{reference_content_id}",
    RATING: "/searched-result/rating",
    REPORT: "/searched-result/report",
  },
  HANDOUTS: {
    ALL: "/handout/all",
    CREATE: "/handout/create",
    EDIT: "/handout/edit",
    DELETE: "/handout/delete/{id}",
  },
  FOLDERS: {
    CREATE: "/folders/create",
    SAVE_CONTENT: "/folders/save-content",
    STRUCTURE: "/folders/structure",
    GET_FOLDER: "/folders/{id}/details",
    POSTED_STRUCTURE: "/folders/posted-structure",
    MOVE_CONTENT: "/folders/move-content",
    DELETE_CONTENT: "/folders/delete-content",
    DELETE_FOLDER: "/folders/delete-folder",
    RENAME_CONTENT: "/folders/rename-content",
    RENAME_FOLDER: "/folders/rename-folder",
  },
  CONTENT: {
    PUBLISHED: "/content/published",
    RETRIEVE: "/content/retrieve",
    STATUS: "/content/status",
    CONTENT_STATUS: "/content/{content_id}/status",
    BY_STATUS: "/content/by-status/{status}",
    CONTENT_BY_ID: "/content/{content_id}",
    DUPLICATE_CONTENT: "/content/duplicate/{content_id}",
  },
  HEALTH_HISTORY: {
    GET: "/health-history",
    POST: "/health-history",
  },
  PRACTITIONER: {
    CREATE_CLIENT: "/practitioner/create-client",
    MANAGED_CLIENTS: "/practitioner/managed-clients",
    SWITCH_CLIENT: "/practitioner/switch-client",
  },
  MENOPAUSE: {
    GET_SYMPTOMS: "/folders/symptoms-subfolders",
    POST_SYMPTOMS: "/menopause/save-symptoms",
    GET_RECOMMENDATIONS: "/menopause/recommendations",
  },
  COACH_ADMIN: {
    GET_CLIENTS: "/coach/managed-clients",
    POST_CLIENT: "/coach/invite-client",
    GET_CLIENT_PROFILE: "/coach/client/{client_id}/profile",
    DELETE_CLIENT: "/coach/client/{client_id}",
    GET_CLIENT_INFO: "/coach/managed-client/get-info/{client_id}",
    PUT_CLIENT_INFO: "/coach/managed-client/edit-info/{client_id}",
    AI_LEARNING_SEARCH: "/ai-learning-search",
    GET_SESSION: "/coach-session/{chat_id}",
    SHARE_CONTENT: "/coach/content-share",
    GET_SHARED_ACCESS: "/coach/{content_id}/shared-access",
    REVOKE_CONTENT_ACCESS: "/coach/revoke-content-access",
    CREATE_FOLDER: "/folders/create",
    SAVE_TO_FOLDER: "/folders/save-content",
    GET_FOLDERS: "/folders/structure",
    GET_FOLDER_DETAILS: "/folders/{folder_id}/details",
    MOVE_FOLDER_CONTENT: "/folders/move-content",
    DELETE_FOLDER_CONTENT: "/folders/delete-content",
    DELETE_FOLDER: "/folders/delete-folder",
    RENAME_CONTENT: "/folders/rename-content",
    EDIT_FOLDER: "/folders/edit-folder",
    UPDATE_FOLDER_CONTENT: "/folders/update-folder-content",
    GET_CONTENT: "/content/retrieve",
    GET_REVIEWERS: "/user/reviewers",
    CHANGE_STATUS: "/library/status",
    RATE_CONTENT: "/coach/rate-content",
  },

  DOCUMENTS: {
    DETAILS: "/content/retrieve",
  },
};

export const EXCLUDE_TOKEN_ENDPOINTS = [
  "/user/login",
  "/user/signup",
  "/ai-personalized-search/",
  "/update-chat-title",
  "/update-folder-content",
  "/chat/{chat_id}",
];
