export const API_ROUTES = {
  USER: {
    SET_NEW_PASSWORD: "/user/reset-password",
    EXIST: "/user-exist/{email}",
    SIGNUP: "/user/signup",
    COMPLETE_SIGNUP: "/user/complete-signup",
    LOGIN: "/user/login",
    FORGOT_PASSWORD: "/user/forgot-password",
    PROFILE: "/user/profile",
    DELETE_ACCOUNT: "/user/delete-account",
    VERIFY_RESET_TOKEN: "/user/verify-reset-token",
    ONBOARD_USER: "/coach/onboarding",
    ONBOARD_CLIENT: "/client/onboarding",
    GET_ONBOARDING_USER: "/client/onboarding",
    SIGNOUT: "/user/signout",
    CHANGE_PASSWORD: "/user/change-password",
    DOWNLOAD_PHOTO: "/profile/photo/{filename}",
    REFER_FRIEND: "/user/refer-friend",
    GET_REFERRAL_INVITATION: "/referral/invitation-details/{token}",
    GET_ONBOARDING_STATUS: "/user/onboarding-status",
    CHECK_PENDING_INVITE: "/client/check-pending-invite",
    REQUEST_PASSWORDLESS_LOGIN: "/user/email-login",
    VERIFY_PASSWORDLESS_LOGIN: "/user/verify-login",
  },
  CLIENT: {
    GET_INVITATION_DETAILS: "/client/invitation-details/{token}",
    GET_SHARED_COACH_CONTENT: "/client/shared-coach-content/{content_id}",
    ACCEPT_COACH_INVITE: "/client/accept-coach-invite",
    GET_SHARED_CONTENT_BY_ID: "/client/shared-coach-content/{content_id}",
    GET_LIBRARY_CONTENT: "/client/library",
    REQUEST_INVITE: "/client/request-new-invite",
    GET_PROFILE: "/client/profile",
    UPDATE_PROFILE: "/client/profile",
    GET_COACHES: "/client/coaches",
    GET_COACH_PROFILE: "/client/coach/{coach_id}/profile",
    DOWNLOAD_COACH_PHOTO: "/client/coach/{coach_id}/photo/{filename}",
  },
  AI: {
    SEARCH: "/ai-search/",
    LEARNING_SEARCH: "/ai-learning-search/",
    PERSONALIZED_SEARCH: "/ai-personalized-search/",
    UPDATE_CHAT_TITLE: "/update-chat-title",
    UPDATE_FOLDER_CONTENT: "/update-folder-content",
  },
  SEARCH: {
    HISTORY: "/searched-result/history",
    SESSION: "/session/{chat_id}",
    ADMIN_SESSION: "/admin-session/{chat_id}",
    PERSONALIZED_SESSION: "/personalized-session/{reference_content_id}",
    RATING: "/searched-result/rating",
    REPORT: "/searched-result/report",
  },
  HANDOUTS: {
    ALL: "/handout/all",
    CREATE: "/handout/create",
    EDIT: "/handout/edit",
    DELETE: "/handout/delete/{id}",
  },
  FOLDERS: {
    CREATE: "/folders/create",
    SAVE_CONTENT: "/folders/save-content",
    STRUCTURE: "/folders/structure",
    GET_FOLDER: "/folders/{id}/details",
    POSTED_STRUCTURE: "/folders/posted-structure",
    MOVE_CONTENT: "/folders/move-content",
    DELETE_CONTENT: "/folders/delete-content",
    DELETE_FOLDER: "/folders/delete-folder",
    RENAME_CONTENT: "/folders/rename-content",
    RENAME_FOLDER: "/folders/rename-folder",
  },
  CONTENT: {
    PUBLISHED: "/content/published",
    RETRIEVE: "/content/retrieve",
    STATUS: "/content/status",
    CONTENT_STATUS: "/content/{content_id}/status",
    BY_STATUS: "/content/by-status/{status}",
    CONTENT_BY_ID: "/content/{content_id}",
    DUPLICATE_CONTENT: "/content/duplicate",
    EDIT_CONTENT: "/content/edit-content",
    UPDATE_CONTENT_STATUS: "/content/{content_id}/read-status",
    FEEDBACK: "/feedback",
    ADD_HASHTAGS: "/content/hashtags/add",
    DELETE_HASHTAGS: "/content/hashtags/remove",
    GET_CONTENT_HASHTAGS: "/content/hashtags/{content_id}",
    GET_CONTENTS_WITH_SIMILAR_TAGS: "/content/similar-tags",
    GET_ALL_HASHTAGS: "/content/all-hashtags",
    GET_CREATOR_PROFILE: "/creator/{creator_id}/profile",
    DOWNLOAD_CREATOR_PHOTO: "/creator/{creator_id}/photo/{filename}",
    SHARE_EMAIL: "/share/email",
    SHARE_COACH: "/share/coach",
    LIBRARY_STATUS: "/library/status",
    QUIZ_SCORE: "/content/{content_id}/quiz-score",
  },
  HEALTH_HISTORY: {
    GET: "/health-history",
    POST: "/health-history",
    GET_LAB_REPORT: "/health-history/lab-report/{filename}",
  },
  PRACTITIONER: {
    CREATE_CLIENT: "/practitioner/create-client",
    MANAGED_CLIENTS: "/practitioner/managed-clients",
    SWITCH_CLIENT: "/practitioner/switch-client",
  },
  MENOPAUSE: {
    GET_SYMPTOMS: "/folders/symptoms-subfolders",
    POST_SYMPTOMS: "/menopause/save-symptoms",
    GET_RECOMMENDATIONS: "/menopause/recommendations",
  },
  COACH_ADMIN: {
    GET_CLIENTS: "/coach/managed-clients",
    POST_CLIENT: "/coach/invite-client",
    GET_CLIENT_PROFILE: "/coach/client/{client_id}/profile",
    DELETE_CLIENT: "/coach/client/{client_id}",
    GET_CLIENT_INFO: "/coach/managed-client/get-info/{client_id}",
    PUT_CLIENT_INFO: "/coach/managed-client/edit-info/{client_id}",
    AI_LEARNING_SEARCH: "/ai-learning-search",
    AI_LEARNING_CARD_SEARCH: "/ai-learning-card-search",
    GET_SESSION: "/coach-session/{chat_id}",
    SHARE_CONTENT: "/coach/content-share",
    GET_SHARED_ACCESS: "/coach/{content_id}/shared-access",
    REVOKE_CONTENT_ACCESS: "/coach/revoke-content-access",
    CREATE_FOLDER: "/folders/create",
    SAVE_TO_FOLDER: "/folders/save-content",
    GET_FOLDER_DETAILS: "/folders/{folder_id}/details",
    MOVE_FOLDER_CONTENT: "/folders/move-content",
    DELETE_FOLDER_CONTENT: "/folders/delete-content",
    DELETE_FOLDER: "/folders/delete-folder",
    RENAME_CONTENT: "/folders/rename-content",
    EDIT_FOLDER: "/folders/edit-folder",
    UPDATE_FOLDER_CONTENT: "/folders/update-folder-content",
    GET_REVIEWERS: "/user/reviewers",
    CHANGE_STATUS: "/library/status",
    RATE_CONTENT: "/coach/rate-content",
    SEARCH_CONTENT: "/coach/search-content",
    SHARE_FMP: "/coach/fmp-tracker/share",
    POST_FMP: "/coach/client/fmp-tracker/{tracker_id}/entries",
    DELETE_FMP: "/coach/fmp-tracker/{tracker_id}",
    GET_COMPREHENSIVE_CLIENT: "/coach/client/{client_id}/comprehensive-profile",
    GET_LAB_FILE: "/coach/client/{client_id}/labs/download/{file_name}",
    UPDATE_COMPREHENSIVE_CLIENT:
      "/coach/client/{client_id}/comprehensive-update",
    UPDATE_HEALTH_HISTORY: "/coach/client/request-health-history-update",
    DOWNLOAD_LICENSE: "/coach/license/{filename}",
    DELETE_LICENSE: "/coach/license/{filename}",
  },
  DOCUMENTS: {
    DETAILS: "/content/retrieve",
  },
  ADMIN: {
    GET_ALL_USERS: "/admin/users",
    GET_FEEDBACK: "/admin/feedback",
    GET_ALL_CHATS: "admin/chats",
    GET_MESSAGES: "admin/chats/{chat_id}/messages",
    SEND_MESSAGE: "admin/chats/bulk-message",
    GET_FOLDERS: "/admin/folders/structure",
    GET_UNPUBLISHED_CONTENT: "/admin/content/unpublished",
    MANAGE_CONTENT: "/admin/content/manage",
  },
  SYMPTOMS_TRACKER: {
    POST_SYMPTOMS: "/symptom-tracker/log-symptoms/",
    PUT_SYMPTOMS: "/symptom-tracker/symptoms/{record_id}/",
    GET_SYMPTOMS: "/symptom-tracker/{target_date}",
    GET_SUGGESTIONS: "/symptom-tracker/ai-suggestions/",
    DELETE_SYMPTOM: "/symptom-tracker/symptoms/{symptom_id}/",
  },
  CHAT: {
    FETCH_ALL: "/chats",
    FETCH_ONE: "/chats/{chat_id}",
    GET_CHAT_BY_ID: "/chats/{chat_id}",
    SEND_MESSAGE: "/chats/messages",
    CREATE_GROUP_CHAT: "/chats/group",
    UPDATE_GROUP_CHAT: "/chats/{chat_id}",
    UPLOAD_FILE: "/chats/{chat_id}/upload",
    UPLOADED_FILE: "/uploads/chat_files/{filename}",
    UPLOADED_AVATAR: "/uploads/chat_avatars/{filename}",
    FETCH_CHAT_MESSAGES: "/chats/{chat_id}/messages",
    FETCH_CHAT_FILES: "/chats/{chat_id}/files",
    DELETE_MESSAGE: "/chats/{chat_id}/messages/{message_id}",
    SEND_CHAT_NOTE: "/chat-notes",
    GET_ALL_CHAT_NOTES: "/chat-notes/{chat_id}",
    UPDATE_CHAT_NOTE: "/chat-notes/{note_id}",
    DELETE_CHAT_NOTE: "/chat-notes/{note_id}",
    UPLOADED_FILE_CHAT_NOTE: "/chat-notes/uploads/{file_uuid}",
    DELETE_CHAT: "/chat/{chat_id}",
  },
  NOTIFICATIONS: {
    GET_NOTIFICATIONS: "/notifications",
    GET_UNREAD: "/notifications/unread-count",
    MARK_AS_READ: "/notifications/mark-read",
    DISMISS_NOTIFICATION: "/notifications/{notification_id}/dismiss",
    GET_NOTIFICATION_PREFERENCES: "/notifications/preferences",
    UPDATE_NOTIFICATION_PREFERENCES: "/notifications/preferences",
  },
  FILES_LIBRARY: {
    FETCH_ALL: "/files-library/",
    FETCH_ONE: "/files-library/{file_id}",
    UPDATE: "/files-library/{file_id}",
    DELETE: "/files-library/{file_id}",
    DOWNLOAD: "/files-library/{file_id}/download",
    UPLOAD: "/files-library/upload",
    CREATE_FOLDER: "/files-library/create-folder/",
    GET_FOLDER: "/files-library/{folder_id}",
    UPDATE_FOLDER: "/files-library/edit-folder/{folder_id}",
    GET_FOLDER_CONTENTS: "/files-library/{folder_id}/contents",
    DELETE_FOLDER: "/files-library/delete-folder/{folder_id}",
    MOVE_FILES: "/files-library/move-files",
  },
};

export const EXCLUDE_TOKEN_ENDPOINTS = [
  "/user/login",
  "/user/signup",
  "/ai-personalized-search/",
  "/update-folder-content",
  "/chat/{chat_id}",
];
