export const timezoneOptions = [
  "(GMT-05:00) Eastern Time (US & Canada)",
  "(GMT-06:00) Central Time (US & Canada)",
  "(GMT-07:00) Mountain Time (US & Canada)",
  "(GMT-08:00) Pacific Time (US & Canada)",
  "(GMT-09:00) Alaska Time (US & Canada)",
  "(GMT-10:00) Hawaii-Aleutian Time (US)",
  "(GMT-11:00) Midway Island, Samoa",
  "(GMT-12:00) Baker Island, Howland Island",
  "(GMT+00:00) Coordinated Universal Time (UTC)",
  "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "(GMT+02:00) Athens, Bucharest, Istanbul, Minsk",
  "(GMT+03:00) Baghdad, Riyadh, Moscow, St. Petersburg",
  "(GMT+04:00) Abu Dhabi, Muscat, Baku, Tbilisi",
  "(GMT+05:00) Islamabad, Karachi, Tashkent",
  "(GMT+06:00) Almaty, Dhaka, Novosibirsk",
  "(GMT+07:00) Bangkok, Hanoi, Jakarta",
  "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
  "(GMT+09:00) Osaka, Sapporo, Seoul, Tokyo",
  "(GMT+10:00) Brisbane, Canberra, Guam, Melbourne, Sydney",
  "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
  "(GMT+12:00) Auckland, Wellington, Fiji, Kamchatka",
  "(GMT+13:00) Nuku'alofa, Samoa, Tokelau Islands",
  "(GMT+14:00) Line Islands, Phoenix Islands",
  "(GMT+15:00) Chatham Islands, Marquesas Islands",
  "(GMT+16:00) Fiji, Kamchatka, Marshall Islands",
  "(GMT+17:00) Solomon Islands, New Caledonia, Papua New Guinea",
  "(GMT+18:00) Wake Island, Fiji, Kamchatka",
  "(GMT+19:00) Chatham Islands, Marquesas Islands",
  "(GMT+20:00) Line Islands, Phoenix Islands",
  "(GMT+21:00) Samoa, Tokelau Islands",
  "(GMT+22:00) Baker Island, Howland Island",
  "(GMT+23:00) Midway Island, Samoa",
];
