// constants.js
export const professions = [
    { value: "Certified Functional Nutrition Coach", label: "Certified Functional Nutrition Coach" },
    { value: "Licensed Nutritionist", label: "Licensed Nutritionist" },
    { value: "Certified Women's Health Coach", label: "Certified Women's Health Coach" },
    { value: "Certified Fitness Professional", label: "Certified Fitness Professional" },
    { value: "Certified Health Coach", label: "Certified Health Coach" },
    { value: "Healthcare Professional", label: "Healthcare Professional" },
    { value: "Herbalist", label: "Herbalist" },
    { value: "Holistic Healthcare Provider", label: "Holistic Healthcare Provider" },
    { value: "Homeopath", label: "Homeopath" },
    { value: "Licensed Acupuncturist", label: "Licensed Acupuncturist" },
    { value: "Licensed Chiropractor", label: "Licensed Chiropractor" },
    { value: "Licensed Counselor", label: "Licensed Counselor" },
    { value: "Licensed Massage Therapist", label: "Licensed Massage Therapist" },
    { value: "Licensed Medical Doctor", label: "Licensed Medical Doctor" },
    { value: "Licensed Naturopathic Doctor", label: "Licensed Naturopathic Doctor" },
    { value: "Licensed Nurse Practitioner", label: "Licensed Nurse Practitioner" },
    { value: "Licensed Nutritionist", label: "Licensed Nutritionist" },
    { value: "Licensed Optometrist", label: "Licensed Optometrist" },
    { value: "Licensed Osteopathic Physician", label: "Licensed Osteopathic Physician" },
    { value: "Licensed Physical/Occupational Therapist", label: "Licensed Physical/Occupational Therapist" },
    { value: "Licensed Physician Assistant", label: "Licensed Physician Assistant" },
    { value: "Licensed Practitioner of Oriental Medicine", label: "Licensed Practitioner of Oriental Medicine" },
    { value: "Licensed Veterinary Practitioner", label: "Licensed Veterinary Practitioner" },
    { value: "Medical/Osteopathic Doctor", label: "Medical/Osteopathic Doctor" },
    { value: "Naturopathic Doctor (CNME)", label: "Naturopathic Doctor (CNME)" },
    { value: "Nurse", label: "Nurse" },
    { value: "Nutritional Counselor", label: "Nutritional Counselor" },
    { value: "Other licensed Healthcare Providers", label: "Other licensed Healthcare Providers" },
    { value: "Registered Dietitian", label: "Registered Dietitian" },
    { value: "Registered Midwife", label: "Registered Midwife" },
    { value: "Registered Nurse", label: "Registered Nurse" },
    { value: "Registered Pharmacist", label: "Registered Pharmacist" },
    { value: "Student", label: "Student" },
    { value: "Other", label: "Other" }
];
