import { HealthHistory, HealthHistoryPostData } from "entities/health-history";
import z from "zod";
import { baseSchema } from "./ui";

export const mapHealthHistoryToFormDefaults = (
  healthHistory?: HealthHistory
) => {
  return {
    age: healthHistory?.age?.toString() ?? "",
    maritalStatus: healthHistory?.marital_status ?? "",
    job: healthHistory?.job ?? "",
    children: healthHistory?.no_children ?? "",
    menopauseStatus: healthHistory?.menopause_status ?? "",
    otherChallenges: healthHistory?.other_challenges ?? "",
    strategiesTried: healthHistory?.tried_strategies ?? "",
    diagnosedConditions: healthHistory?.diagnosed_conditions ?? "",
    geneticTraits: healthHistory?.genetic_traits ?? "",
    maternalSide: healthHistory?.family_health_history ?? "",
    paternalSide: healthHistory?.support_system ?? "",
    notableConcern: healthHistory?.family_health_history ?? "",
    stressLevel: healthHistory?.stress_levels ?? "",
    takeout: healthHistory?.takeout_food ?? "",
    homeCooked: healthHistory?.cook_at_home ?? "",
    dietType: healthHistory?.specific_diet ?? "",
    exercise: healthHistory?.exercise_habits ?? "",
    limitations: healthHistory?.lifestyle_limitations ?? "",
    medications: healthHistory?.medications ?? "",
    period: healthHistory?.menstrual_cycle_status ?? "",
    sexLife: healthHistory?.sex_life ?? "",
    supportSystem: healthHistory?.support_system ?? "",
    goals: healthHistory?.health_goals ?? "",
    gender: healthHistory?.gender ?? "",
    height: healthHistory?.height ?? "",
    weight: healthHistory?.weight ?? "",
    supplements: healthHistory?.supplements ?? "",
    allergies: healthHistory?.allergies_intolerances ?? "",
    dietPattern: healthHistory?.diet_pattern ?? "",
    kindOfFood: healthHistory?.kind_of_food ?? "",
    eatDecision: healthHistory?.eat_decision ?? "",
    sleepQuality: healthHistory?.sleep_quality ?? "",
    energyLevels: healthHistory?.energy_levels ?? "",
    hormoneTherapy: healthHistory?.hormone_replacement_therapy ?? "",
    fertilityConcerns: healthHistory?.fertility_concerns ?? "",
    birthControlUse: healthHistory?.birth_control_use ?? "",
    bloodSugarConcerns: healthHistory?.blood_sugar_concerns ?? "",
    digestiveIssues: healthHistory?.digestive_issues ?? "",
    recentLabTests: healthHistory?.recent_lab_tests ?? false,
    labResultsFile: healthHistory?.lab_results_file ?? null,
    whyGoals: healthHistory?.why_these_goals ?? "",
    resultTimeline: healthHistory?.desired_results_timeline ?? "",
    healthApproach: healthHistory?.health_approach_preference ?? "",
    privacyConsent: healthHistory?.privacy_consent ?? false,
    followUpRecommendation: healthHistory?.follow_up_recommendation ?? "",
    recommendationDestination: healthHistory?.recommendation_destination ?? "",
  };
};

export const mapFormToPostData = (
  formValues: z.infer<typeof baseSchema>
): HealthHistoryPostData => ({
  age: parseInt(formValues.age ?? "0", 10),
  marital_status: formValues.maritalStatus,
  job: formValues.job,
  no_children: formValues.children,
  menopause_status: formValues.menopauseStatus,
  current_health_concerns: formValues.mainSymptoms,
  other_challenges: formValues.otherChallenges,
  tried_strategies: formValues.strategiesTried,
  diagnosed_conditions: formValues.diagnosedConditions,
  maternal_health_history: formValues.maternalSide,
  paternal_health_history: formValues.paternalSide,
  family_health_history: formValues.geneticTraits,
  lifestyle_information: formValues.lifestyleInfo,
  takeout_food: formValues.takeout,
  cook_at_home: formValues.homeCooked,
  specific_diet: formValues.dietType,
  exercise_habits: formValues.exercise,
  lifestyle_limitations: formValues.limitations,
  medications: formValues.medications,
  menstrual_cycle_status: formValues.period,
  sex_life: formValues.sexLife,
  support_system: formValues.supportSystem,
  health_goals: formValues.goals,
  gender: "Female",
  height: "",
  weight: "",
  supplements: "",
  allergies_intolerances: "",
  eat_decision: formValues.limitations ?? "",
  kind_of_food: "",
  diet_pattern: "",
  sleep_quality: "",
  stress_levels: "",
  energy_levels: "",
  hormone_replacement_therapy: "",
  fertility_concerns: "",
  birth_control_use: "",
  blood_sugar_concerns: "",
  digestive_issues: "",
  recent_lab_tests: false,
  why_these_goals: "",
  desired_results_timeline: "",
  health_approach_preference: "",
  privacy_consent: true,
  follow_up_recommendations: "",
});
