import { HealthHistory, HealthHistoryPostData } from "entities/health-history";
import z from "zod";
import { baseSchema } from "./ui";

export const mapHealthHistoryToFormDefaults = (
  healthHistory?: HealthHistory
) => {
  return {
    age: healthHistory?.age?.toString() ?? "",
    maritalStatus: "",
    job: "",
    children: "",
    menopauseStatus: healthHistory?.menstrual_cycle_status ?? "",
    mainSymptoms: healthHistory?.current_health_concerns ?? "",
    otherChallenges: "",
    strategiesTried: "",
    diagnosedConditions: healthHistory?.diagnosed_conditions ?? "",
    geneticTraits: "",
    maternalSide: healthHistory?.family_health_history ?? "",
    paternalSide: "",
    notableConcern: "",
    stressLevel: healthHistory?.stress_levels ?? "",
    takeout: healthHistory?.takeout_food ?? "",
    homeCooked: healthHistory?.cook_at_home ?? "",
    dietType: healthHistory?.specific_diet ?? "",
    exercise: healthHistory?.exercise_habits ?? "",
    limitations: "",
    medications: healthHistory?.medications ?? "",
    period: healthHistory?.menstrual_cycle_status ?? "",
    sexLife: "",
    supportSystem: "",
    goals: healthHistory?.health_goals ?? "",

    gender: healthHistory?.gender ?? "",
    height: healthHistory?.height ?? "",
    weight: healthHistory?.weight ?? "",
    supplements: healthHistory?.supplements ?? "",
    allergies: healthHistory?.allergies_intolerances ?? "",
    dietPattern: healthHistory?.diet_pattern ?? "",
    kindOfFood: healthHistory?.kind_of_food ?? "",
    eatDecision: healthHistory?.eat_decision ?? "",
    sleepQuality: healthHistory?.sleep_quality ?? "",
    energyLevels: healthHistory?.energy_levels ?? "",
    hormoneTherapy: healthHistory?.hormone_replacement_therapy ?? "",
    fertilityConcerns: healthHistory?.fertility_concerns ?? "",
    birthControlUse: healthHistory?.birth_control_use ?? "",
    bloodSugarConcerns: healthHistory?.blood_sugar_concerns ?? "",
    digestiveIssues: healthHistory?.digestive_issues ?? "",
    recentLabTests: healthHistory?.recent_lab_tests ?? false,
    labResultsFile: healthHistory?.lab_results_file ?? null,
    whyGoals: healthHistory?.why_these_goals ?? "",
    resultTimeline: healthHistory?.desired_results_timeline ?? "",
    healthApproach: healthHistory?.health_approach_preference ?? "",
    privacyConsent: healthHistory?.privacy_consent ?? false,
    followUpRecommendation: healthHistory?.follow_up_recommendation ?? "",
    recommendationDestination: healthHistory?.recommendation_destination ?? "",
  };
};

export const mapFormToPostData = (
  formValues: z.infer<typeof baseSchema>
): HealthHistoryPostData => ({
  age: parseInt(formValues.age ?? "0", 10),
  gender: "Female",
  height: "",
  weight: "",
  current_health_concerns: formValues.mainSymptoms ?? "",
  diagnosed_conditions: formValues.diagnosedConditions ?? "",
  medications: formValues.medications ?? "",
  supplements: "",
  allergies_intolerances: "",
  family_health_history:
    `${formValues.maternalSide}, ${formValues.paternalSide}`.trim() ?? "",
  specific_diet: formValues.dietType ?? "",
  exercise_habits: formValues.exercise ?? "",
  eat_decision: formValues.limitations ?? "",
  cook_at_home: formValues.homeCooked ?? "",
  takeout_food: formValues.takeout ?? "",
  kind_of_food: "",
  diet_pattern: "",
  sleep_quality: "",
  stress_levels: formValues.stressLevel ?? "",
  energy_levels: "",
  menstrual_cycle_status: formValues.period ?? "",
  hormone_replacement_therapy: "",
  fertility_concerns: "",
  birth_control_use: "",
  blood_sugar_concerns: "",
  digestive_issues: "",
  recent_lab_tests: false,
  health_goals: formValues.goals ?? "",
  why_these_goals: "",
  desired_results_timeline: "",
  health_approach_preference: "",
  privacy_consent: true,
  follow_up_recommendations: "",
});
