import { IFolder } from "entities/folder";
import { MOCK_DOCUMENT } from "../document/mock";

export const possibleClientNames = [
  "Kurt Bates",
  "Kathy Pacheco",
  "Eddie Lake",
  "Iva Ryan",
  "Dennis Callis",
];

export const FOLDERS: IFolder[] = [
  {
    id: "1",
    name: "Mood Swings",
    documents: [
      MOCK_DOCUMENT[21],
      MOCK_DOCUMENT[22],
      MOCK_DOCUMENT[23],
      MOCK_DOCUMENT[24],
      MOCK_DOCUMENT[25],
      MOCK_DOCUMENT[26],
      MOCK_DOCUMENT[27],
      MOCK_DOCUMENT[28],
      MOCK_DOCUMENT[29],
      MOCK_DOCUMENT[30],
    ],
    status: "ready-to-publish",
    reviewers: ["John Doe", "Jane Smith"],
    clients: [
      "Amanda Francis",
      "Kathy Pacheco",
      "Dennis Callis",
      "John Dukes",
      "Katie Sims",
    ],
    files: ["file1.txt", "file2.txt"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[31],
      MOCK_DOCUMENT[32],
      MOCK_DOCUMENT[33],
      MOCK_DOCUMENT[34],
      MOCK_DOCUMENT[35],
      MOCK_DOCUMENT[36],
      MOCK_DOCUMENT[37],
      MOCK_DOCUMENT[38],
      MOCK_DOCUMENT[39],
      MOCK_DOCUMENT[30],
    ],
    status: "ready-to-publish",
    reviewers: ["Alice Johnson"],
    files: ["file3.txt"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[11],
      MOCK_DOCUMENT[12],
      MOCK_DOCUMENT[13],
      MOCK_DOCUMENT[14],
      MOCK_DOCUMENT[15],
      MOCK_DOCUMENT[16],
      MOCK_DOCUMENT[17],
      MOCK_DOCUMENT[18],
      MOCK_DOCUMENT[19],
      MOCK_DOCUMENT[20],
    ],
    status: "ready-to-publish",
    reviewers: ["Alice Johnson"],
    files: ["file3.txt"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[11],
      MOCK_DOCUMENT[12],
      MOCK_DOCUMENT[13],
      MOCK_DOCUMENT[14],
      MOCK_DOCUMENT[15],
      MOCK_DOCUMENT[16],
      MOCK_DOCUMENT[17],
      MOCK_DOCUMENT[18],
      MOCK_DOCUMENT[19],
      MOCK_DOCUMENT[20],
    ],
    status: "ready-to-publish",
    reviewers: ["Alice Johnson"],
    files: ["file3.txt"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "published",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Perimenopause",
    documents: [
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
      MOCK_DOCUMENT[41],
    ],
    status: "archived",
    reviewers: ["Alice Johnson", "Alice Johnson"],
    files: [
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
      "file3.txt",
    ],
    author: "VITAI",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
